apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pv
  namespace: test-alpha-01
spec:
  storageClassName: demo-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
