apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: demo-sc
  hostPath:
    path: /tmp/demo-storage
