apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/demo-logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

